spring.application.name=researchAssistant
gemini.api.url=https://generativelanguage.googleapis.com/v1beta/models/gemini-flash-latest:generateContent?key=
gemini.api.key=${GEMINI_KEY}
spring.datasource.url=${DB_URL:jdbc:postgresql://localhost:5432/ResearchDB}
spring.datasource.username=postgres
spring.datasource.password=takai
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

#springdoc.swagger-ui.path=/api-docs
#spring.main.allow-bean-definition-overriding=true

app.api.key=my-super-secret-dev-key